### ISSUE TITLE
Running react component outside of AEM

### ISSUE THREAD

**Issue by vineet18** [sinnerschrader/aem-react-js#19]
I am able to render react components in AEM and it is working fine. Not sure if this is an issue really but wanted to know if all these react components can be executed/rendered outside of AEM as I see react templates referring to some of the AEM APIs?

**Comment by stemey** [comment]
It is possible to use "vanilla" react components that have no dependencies on AEM. You can even use stateless react components. See [docs](https://sinnerschrader.github.io/aem-react/#subnav_2_5).

I personally have used vanilla components created for a living style guide called [patternplate](https://github.com/sinnerschrader/patternplate) and then automatically deployed them in AEM. You just need to register the vanilla components programmatically.
